server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    # Tout renvoie vers index.html (landing + 404)
    error_page 404 /index.html;

    location / {
        try_files $uri /index.html;
    }

    location = /health {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
